# Generated by Django 5.0.6 on 2024-05-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
